#:schema node_modules/wrangler/config-schema.json
name = "jayc"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "jayc-db"
database_id = "8053e751-6dc2-4a70-a94d-7cc2badaa007"
migrations_dir = "migrations"
